### ISSUE TITLE
Website not redirecting back

### ISSUE THREAD

**Issue by FransiTsena** [abeyshiferaw0/yenepay_flutter#1]
![image](https://user-images.githubusercontent.com/94781526/156975432-7a28189b-f9c8-483c-85df-bed71283b808.png)
The 'Continue to Merchant site not working' although the manifest was configured correctly.

Here is the code i have used to start the transaction
`YenepayFlutter.startPayment(
                  isTestEnv: true,
                  yenepayParameters: YenepayParameters(
                    process: YenepayProcess.Express,
                    merchantId: "SB1415",
                    items: [
                      YenepayItem(
                        itemId: 'Premium Subscription',
                        unitPrice: amount!.toDouble(),
                        quantity: 1,
                        itemName: '$invoice',
                      ),
                    ],
                  ),
                );`

**Comment by abeyshiferaw0** [comment]
the package is working fine, when i am testing it, may be take a look at the manifest and main.dart file in the example project and see if you're  missing any thing.
